export enum LIST_CODES {
  TOTAL_TAREFAS = 'TOTAL_TAREFAS',
  TAREFAS_A_FAZER = 'TAREFAS_A_FAZER',
  EM_ANDAMENTO = 'EM_ANDAMENTO',
  FEITO = 'FEITO',
  A_REVISAR = 'A_REVISAR',
  REVISADO = 'REVISADO',
  REFAZENDO = 'REFAZENDO',
  CONCLUIDO = 'CONCLUIDO',
}
