export enum LIST_CODES {
  BACKLOG = 'BACKLOG',
  SPRINT_BACKLOG = 'SPRINT_BACKLOG',
  DEVELOPMENT = 'DEVELOPMENT',
  DONE_DEVELOPMENT = 'DONE_DEVELOPMENT',
  TEST = 'TEST',
  DONE_TEST = 'DONE_TEST',
  REWORK = 'REWORK',
  DONE = 'DONE',
}
